---
deployment:
  tasks:
    - export DEPLOYPATH=/home/traincu/beta.traincu.com
    - /bin/cp -r public/index.php $DEPLOYPATH
    - /bin/cp -r public/.htaccess $DEPLOYPATH
    - /bin/cp * $DEPLOYPATH
